/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shrms;

import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 泊
 */
public class SchoolView extends javax.swing.JFrame {

    /**
     * Creates new form SdeptView
     */
    public SchoolView() {
        initComponents();
        
        setVisible(true);
        setLocationRelativeTo(null);
        //窗体图标插入图片
        URL imgUrl = LoginView.class.getClassLoader().getResource("\\image\\3.jpg");
        setIconImage(new ImageIcon(imgUrl).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scnoTxt = new javax.swing.JTextField();
        tnoTxt = new javax.swing.JTextField();
        psTxt = new javax.swing.JTextField();
        jsTxt = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        insertBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        selBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hsTxt = new javax.swing.JTextField();
        csTxt = new javax.swing.JTextField();
        gsTxt = new javax.swing.JTextField();
        docTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("部门信息查询");

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("学籍编号：");
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 40));

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("职工名称：");
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 40));

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setText("小学：");
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 40));

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel4.setText("初中：");
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 40));

        scnoTxt.setPreferredSize(new java.awt.Dimension(150, 40));
        scnoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scnoTxtActionPerformed(evt);
            }
        });

        tnoTxt.setPreferredSize(new java.awt.Dimension(150, 40));

        psTxt.setPreferredSize(new java.awt.Dimension(150, 40));
        psTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psTxtActionPerformed(evt);
            }
        });

        jsTxt.setPreferredSize(new java.awt.Dimension(150, 40));

        updateBtn.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        updateBtn.setText("修改");
        updateBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        insertBtn.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        insertBtn.setText("添加");
        insertBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        delBtn.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        delBtn.setText("删除");
        delBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        selBtn.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        selBtn.setText("查询");
        selBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        selBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel5.setText("高中：");
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 40));

        jLabel6.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel6.setText("本科：");
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 40));

        jLabel7.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel7.setText("硕士：");
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 40));

        hsTxt.setPreferredSize(new java.awt.Dimension(150, 40));
        hsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsTxtActionPerformed(evt);
            }
        });

        csTxt.setPreferredSize(new java.awt.Dimension(150, 40));
        csTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csTxtActionPerformed(evt);
            }
        });

        gsTxt.setPreferredSize(new java.awt.Dimension(150, 40));
        gsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gsTxtActionPerformed(evt);
            }
        });

        docTxt.setPreferredSize(new java.awt.Dimension(150, 40));
        docTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docTxtActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel8.setText("博士：");
        jLabel8.setPreferredSize(new java.awt.Dimension(120, 40));

        backBtn.setText("返回");
        backBtn.setPreferredSize(new java.awt.Dimension(80, 40));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(psTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(csTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(docTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(106, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addComponent(selBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(docTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void psTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psTxtActionPerformed

    private void csTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csTxtActionPerformed

    private void hsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hsTxtActionPerformed

    private void gsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gsTxtActionPerformed

    private void docTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docTxtActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainView();
    }//GEN-LAST:event_backBtnActionPerformed

    private void scnoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scnoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scnoTxtActionPerformed

    private void selBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selBtnActionPerformed
        // TODO add your handling code here:
        String scno=scnoTxt.getText();
        String tno=tnoTxt.getText();
        String ps=psTxt.getText();
        String js=jsTxt.getText();
        String hs=hsTxt.getText();
        String cs=csTxt.getText();
        String gs=gsTxt.getText();
        String doc=docTxt.getText();
        try{
            Connection con;
            Statement sql;
            String url,userName,userPwd;
            url="jdbc:sqlserver://localhost:1433;DatabaseName=SHRMS";
            userName="sa";
            userPwd="123456";
            con=DriverManager.getConnection(url,userName,userPwd);
            sql=con.createStatement();
            
            String  strSQL="(Select * from school where scno='"+scnoTxt.getText()+"' )";
            ResultSet rs=sql.executeQuery(strSQL);
            System.out.print(rs);

            if(rs.next())
            {
                    scnoTxt.setText(rs.getString("scno"));
                    tnoTxt.setText(rs.getString("tno"));
                    psTxt.setText(rs.getString("ps"));
                    jsTxt.setText(rs.getString("js"));
                    hsTxt.setText(rs.getString("hs"));
                    csTxt.setText(rs.getString("cs"));
                    gsTxt.setText(rs.getString("gs"));
                    docTxt.setText(rs.getString("doc"));
                    JOptionPane.showMessageDialog(null, "查询成功");
            }
            else
            { 
                JOptionPane.showMessageDialog(null, "您查询的信息不存在，请重新输入");
            }
            con.close();
                //关闭数据库连接	
            } 
	catch (SQLException ex) {
		System.out.println(ex);
        }
    }//GEN-LAST:event_selBtnActionPerformed

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        // TODO add your handling code here:
        String scno=scnoTxt.getText();
        String tno=tnoTxt.getText();
        String ps=psTxt.getText();
        String js=jsTxt.getText();
        String hs=hsTxt.getText();
        String cs=csTxt.getText();
        String gs=gsTxt.getText();
        String doc=docTxt.getText();
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
        try{
            Connection con;
            Statement sql;
            String url,userName,userPwd;
            url="jdbc:sqlserver://localhost:1433;DatabaseName=SHRMS";
            userName="sa";
            userPwd="123456";
            con=DriverManager.getConnection(url,userName,userPwd);
            sql=con.createStatement();
            Statement st=con.createStatement();
            String  strSQL="insert into school values('"+scno+"','"+tno+"','"+ps+"','"+js+"','"+hs+"','"+cs+"','"+gs+"','"+doc+"');";
            int rs=st.executeUpdate(strSQL);
                if(rs==1) {
                        JOptionPane.showMessageDialog(null,"添加成功");
                }
                else{
                        JOptionPane.showMessageDialog(null,"添加失败");
                }
            con.close();
          //关闭数据库连接
        }
        catch(SQLException exp){
            System.out.println();
        }
    }//GEN-LAST:event_insertBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String scno=scnoTxt.getText();
        String tno=tnoTxt.getText();
        String ps=psTxt.getText();
        String js=jsTxt.getText();
        String hs=hsTxt.getText();
        String cs=csTxt.getText();
        String gs=gsTxt.getText();
        String doc=docTxt.getText();
        try{
            Connection con;
            Statement sql;
            String url,userName,userPwd;
            url="jdbc:sqlserver://localhost:1433;DatabaseName=SHRMS";
            userName="sa";
            userPwd="123456";
            con=DriverManager.getConnection(url,userName,userPwd);
            sql=con.createStatement();
            Statement st=con.createStatement();
            
            String  strSQL1="update school set tno='"+tno+"' where scno='"+scno+"'";
            String  strSQL2="update school set ps='"+tno+"' where scno='"+scno+"'";
            String  strSQL3="update school set js='"+tno+"' where scno='"+scno+"'";
            String  strSQL4="update school set hs='"+tno+"' where scno='"+scno+"'";
            String  strSQL5="update school set cs='"+tno+"' where scno='"+scno+"'";
            String  strSQL6="update school set gs='"+tno+"' where scno='"+scno+"'";
            String  strSQL7="update school set doc='"+tno+"' where scno='"+scno+"'";
		int rs1=st.executeUpdate(strSQL1);
		int rs2=st.executeUpdate(strSQL2);
		int rs3=st.executeUpdate(strSQL3);
                int rs5=st.executeUpdate(strSQL5);
		int rs4=st.executeUpdate(strSQL4);
		int rs6=st.executeUpdate(strSQL6);
                int rs7=st.executeUpdate(strSQL7);
		if(rs1==1&&rs2==1&&rs3==1&&rs4==1&&rs5==1&&rs6==1&&rs7==1) {
			JOptionPane.showMessageDialog(null,"修改成功");
		}
		else{
			JOptionPane.showMessageDialog(null,"修改失败");
		}
	    con.close();
	   
                    //关闭数据库连接	
                } 
	catch (SQLException ex) {
		System.out.println(ex);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
        String scno=scnoTxt.getText();
        String tno=tnoTxt.getText();
        String ps=psTxt.getText();
        String js=jsTxt.getText();
        String hs=hsTxt.getText();
        String cs=csTxt.getText();
        String gs=gsTxt.getText();
        String doc=docTxt.getText();
        try{
            Connection con;
            Statement sql;
            String url,userName,userPwd;
            url="jdbc:sqlserver://localhost:1433;DatabaseName=SHRMS";
            userName="sa";
            userPwd="123456";
            con=DriverManager.getConnection(url,userName,userPwd);
            sql=con.createStatement();
            Statement st=con.createStatement();
            
            String strSQL="delete  from  school where sno='"+scno+"' ";
				  
            int rs=st.executeUpdate(strSQL);
                if(rs==1) {
                        JOptionPane.showMessageDialog(null,"删除成功");
                }
                else{
                        JOptionPane.showMessageDialog(null,"删除失败");
                }
	    con.close();
	   
                    //关闭数据库连接	
                } 
	catch (SQLException ex) {
		System.out.println(ex);
        }
    }//GEN-LAST:event_delBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchoolView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField csTxt;
    private javax.swing.JButton delBtn;
    private javax.swing.JTextField docTxt;
    private javax.swing.JTextField gsTxt;
    private javax.swing.JTextField hsTxt;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jsTxt;
    private javax.swing.JTextField psTxt;
    private javax.swing.JTextField scnoTxt;
    private javax.swing.JButton selBtn;
    private javax.swing.JTextField tnoTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
